# Generated by Django 4.2.9 on 2024-08-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('nights', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoiced_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
