# Generated by Django 4.2.9 on 2024-08-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sr_no',
            new_name='id',
        ),
    ]
