# Generated by Django 4.2.9 on 2024-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_sr_no_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('biller_no', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('vessel_name', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=6)),
                ('claimable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
            ],
        ),
    ]
